# Generated by Django 2.0.2 on 2018-03-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDuplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uw_client_id', models.IntegerField()),
                ('assessment_date', models.DateTimeField()),
                ('assessing_organization', models.CharField(max_length=300)),
                ('assessment_score', models.IntegerField()),
            ],
        ),
    ]
